### ISSUE TITLE
Segmentation Violation when running sqlboiler bin

### ISSUE THREAD

**Issue by nicored** [vattle/sqlboiler#130]
If you're having a generation problem please answer these questions before submitting your issue. Thanks!

### What version of SQLBoiler are you using (`sqlboiler --version`)?
`SQLBoiler v2.1.7`

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
```shell
sqlboiler postgres --basedir /Users/nico/go/src/github.com/vattle/sqlboiler -d
```

### If this happened at runtime what code produced the issue? (if not applicable leave blank)
N/A

### What is the output of the command above with the `-d` flag added to it? (Provided you are comfortable sharing this, it contains a blueprint of your schema)
```shell
[{"Name":"data","SchemaName":"","Columns":[{"Name":"id","Type":"int","DBType":"integer","Default":"nextval('data_id_seq'::regclass)","Nullable":false,"Unique":true,"Validated":false,"ArrType":null,"UDTName":"int4","FullDBType":""},{"Name":"data_input","Type":"null.String","DBType":"character varying","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"varchar","FullDBType":""},{"Name":"timestamp","Type":"null.Time","DBType":"timestamp without time zone","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"timestamp","FullDBType":""},{"Name":"casing_pressure","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"casing_pressure_average_yesterday","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"downhole_gauge_fluid_level_above_downhole_sensor_estimated","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"downhole_gauge_fluid_level_from_surface_estimated","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"downhole_gauge_pressure","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"downhole_gauge_pressure_average_yesterday","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"downhole_gauge_sensor_depth_from_rotary_table","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"downhole_gauge_temperature","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"downhole_gauge_temperature_averge_yesterday","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"downhole_gauge_type","Type":"null.String","DBType":"character varying","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"varchar","FullDBType":""},{"Name":"fcv_output","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"gas_flow_dp","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"gas_flow_energy","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"gas_flow_energy_total_yesterday","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"gas_flow_volume","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"gas_flow_volume_total_yesterday","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"gas_flow_orifice_diameter","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"gas_flow_orifice_upstream_pipe_internal_diameter","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"gas_gathering_pressure","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"gas_gathering_pressure_average_yesterday","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"lcv_output","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"lcv_position_feedback","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"motor_current","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"motor_power","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"motor_speed","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"motor_torque","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"pcv_output","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"pcv_position_feedback","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"pump_speed_actual","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"pump_speed_average_yesterday","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"pump_torque","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"pump_torque_average_yesterday","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"pump_torque_max_today","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"pump_to_vsd_speed_command","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"separator_differential_pressure","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"separator_gas_pressure","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"separator_level","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"separator_pressure_average_yesterday","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"separator_pressure_max_today","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"sheave_ratio","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"tubing_flow_meter","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"tubing_pressure","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"tubing_pressure_average_yesterday","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"tubing_size_type","Type":"null.Time","DBType":"date","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"date","FullDBType":""},{"Name":"vsd_frequency","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"vsd_mode","Type":"null.String","DBType":"character varying","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"varchar","FullDBType":""},{"Name":"vsd_output","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"vsd_running","Type":"null.Bool","DBType":"boolean","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"bool","FullDBType":""},{"Name":"vsd_temperature","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"wec_pcp_efficiency","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"wec_pcp_efficiency_alarm","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"wec_pcp_theoretical_pump_displacement","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"wec_pump_max_speed_setpoint","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"wec_pump_min_speed_setpoint","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"wec_pump_speed_sampled_average","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"wec_pump_speed_setpoint","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"wec_pump_trip","Type":"null.String","DBType":"character varying","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"varchar","FullDBType":""},{"Name":"wec_slow_pump_to_min_speed_command","Type":"null.String","DBType":"character varying","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"varchar","FullDBType":""},{"Name":"water_flow_avg_5m","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"water_flow_mag_from_separator","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"water_flow_mag_from_separator_total_yesterday","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"water_flow_wedge_sampled_average","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"water_flow_wedge_total_yesterday","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"water_gathering_pressure","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"water_gathering_pressure_average_yesterday","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"wedgemeter_water_flow_avg_5m","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"wellhead_flow_configuration","Type":"null.String","DBType":"character varying","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"varchar","FullDBType":""},{"Name":"wellhead_state","Type":"null.String","DBType":"character varying","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"varchar","FullDBType":""},{"Name":"wellhead_status","Type":"null.Float64","DBType":"numeric","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"numeric","FullDBType":""},{"Name":"wellhead_type","Type":"null.String","DBType":"character varying","Default":"","Nullable":true,"Unique":false,"Validated":false,"ArrType":null,"UDTName":"varchar","FullDBType":""}],"PKey":{"Name":"data_pkey","Columns":["id"]},"FKeys":null,"IsJoinTable":false,"ToOneRelationships":null,"ToManyRelationships":null}]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e3192]

goroutine 1 [running]:
panic(0x4bfa40, 0xc4200120c0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
text/template.errRecover(0xc4202dd598)
	/usr/local/go/src/text/template/exec.go:140 +0x2ad
panic(0x4bfa40, 0xc4200120c0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/vattle/sqlboiler/strmangle.StringMap(0x0, 0xc420143820, 0x1, 0x1, 0x0, 0x0, 0x0)
	/Users/nico/Projects/myredspace/src/github.com/vattle/sqlboiler/strmangle/strmangle.go:399 +0x92
reflect.Value.call(0x4ae120, 0x5a6d78, 0x13, 0x533f3d, 0x4, 0xc4201978f0, 0x2, 0x2, 0xc420163b80, 0x1, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x4ae120, 0x5a6d78, 0x13, 0xc4201978f0, 0x2, 0x2, 0x491dc0, 0xc4202f0960, 0x97)
	/usr/local/go/src/reflect/value.go:302 +0xa4
text/template.(*state).evalCall(0xc4202dd518, 0x4c1440, 0xc42015cdc0, 0x16, 0x4ae120, 0x5a6d78, 0x13, 0x780b40, 0xc420313920, 0xc42033410d, ...)
	/usr/local/go/src/text/template/exec.go:658 +0x530
text/template.(*state).evalFunction(0xc4202dd518, 0x4c1440, 0xc42015cdc0, 0x16, 0xc420313950, 0x780b40, 0xc420313920, 0xc4203106e0, 0x2, 0x2, ...)
	/usr/local/go/src/text/template/exec.go:530 +0x195
text/template.(*state).evalCommand(0xc4202dd518, 0x4c1440, 0xc42015cdc0, 0x16, 0xc420313920, 0x491dc0, 0xc4202f0960, 0x97, 0x491dc0, 0xc4202f0960, ...)
	/usr/local/go/src/text/template/exec.go:427 +0x6f7
text/template.(*state).evalPipeline(0xc4202dd518, 0x4c1440, 0xc42015cdc0, 0x16, 0xc4202f5bd0, 0x4c50a0, 0xc420455c50, 0x97)
	/usr/local/go/src/text/template/exec.go:400 +0xee
text/template.(*state).walk(0xc4202dd518, 0x4c1440, 0xc42015cdc0, 0x16, 0x780a20, 0xc4203139e0)
	/usr/local/go/src/text/template/exec.go:226 +0x423
text/template.(*state).walk(0xc4202dd518, 0x4c1440, 0xc42015cdc0, 0x16, 0x780d20, 0xc42032ee10)
	/usr/local/go/src/text/template/exec.go:234 +0x13d
text/template.(*Template).execute(0xc4202f1c80, 0x778ae0, 0x7a2ae0, 0x4c1440, 0xc42015cdc0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:189 +0x204
text/template.(*Template).Execute(0xc4202f1c80, 0x778ae0, 0x7a2ae0, 0x4c1440, 0xc42015cdc0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:175 +0x53
text/template.(*Template).ExecuteTemplate(0xc4201aeb00, 0x778ae0, 0x7a2ae0, 0xc420137579, 0xb, 0x4c1440, 0xc42015cdc0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:165 +0xb3
github.com/vattle/sqlboiler/boilingcore.executeTemplate(0x7a2ae0, 0xc4201aeb00, 0xc420137579, 0xb, 0xc42015cdc0, 0x0, 0x0)
	/Users/nico/Projects/myredspace/src/github.com/vattle/sqlboiler/boilingcore/output.go:215 +0x81
github.com/vattle/sqlboiler/boilingcore.executeTemplates(0xc420067ec0, 0xc42015cdc0, 0xc420214df0, 0x79ade0, 0x7, 0x7, 0x79ac00, 0x5, 0x5, 0x0, ...)
	/Users/nico/Projects/myredspace/src/github.com/vattle/sqlboiler/boilingcore/output.go:110 +0x23a
github.com/vattle/sqlboiler/boilingcore.generateOutput(0xc420067ec0, 0xc42015cdc0, 0x0, 0x0)
	/Users/nico/Projects/myredspace/src/github.com/vattle/sqlboiler/boilingcore/output.go:38 +0xd6
github.com/vattle/sqlboiler/boilingcore.(*State).Run(0xc420067ec0, 0x1, 0x0, 0x0)
	/Users/nico/Projects/myredspace/src/github.com/vattle/sqlboiler/boilingcore/boilingcore.go:150 +0x5ec
main.run(0xc4201a4b40, 0xc4201ae2c0, 0x1, 0x4, 0x0, 0x0)
	/Users/nico/Projects/myredspace/src/github.com/vattle/sqlboiler/main.go:249 +0x32
github.com/spf13/cobra.(*Command).execute(0xc4201a4b40, 0xc42000c150, 0x4, 0x4, 0xc4201a4b40, 0xc42000c150)
	/Users/nico/Projects/myredspace/src/github.com/spf13/cobra/command.go:646 +0x23e
github.com/spf13/cobra.(*Command).ExecuteC(0xc4201a4b40, 0xc420080870, 0x0, 0x0)
	/Users/nico/Projects/myredspace/src/github.com/spf13/cobra/command.go:737 +0x367
github.com/spf13/cobra.(*Command).Execute(0xc4201a4b40, 0x0, 0x0)
	/Users/nico/Projects/myredspace/src/github.com/spf13/cobra/command.go:695 +0x2b
main.main()
	/Users/nico/Projects/myredspace/src/github.com/vattle/sqlboiler/main.go:97 +0xb2c
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

```sql
DROP TABLE Data;
CREATE TABLE Data(
   id                                                           SERIAL PRIMARY KEY
  ,data_input                                                   VARCHAR(32)
  ,timestamp                                                    TIMESTAMP
  ,casing_pressure                                              NUMERIC
  ,casing_pressure_average_yesterday                            NUMERIC
  ,downhole_gauge_fluid_level_above_downhole_sensor_estimated   NUMERIC
  ,downhole_gauge_fluid_level_from_surface_estimated            NUMERIC
  ,downhole_gauge_pressure                                      NUMERIC
  ,downhole_gauge_pressure_average_yesterday                    NUMERIC
  ,downhole_gauge_sensor_depth_from_rotary_table                NUMERIC
  ,downhole_gauge_temperature                                   NUMERIC
  ,downhole_gauge_temperature_averge_yesterday                  NUMERIC
  ,downhole_gauge_type                                          VARCHAR(32)
  ,fcv_output                                                   NUMERIC
  ,gas_flow_dp                                                  NUMERIC
  ,gas_flow_energy                                              NUMERIC
  ,gas_flow_energy_total_yesterday                              NUMERIC
  ,gas_flow_volume                                              NUMERIC
  ,gas_flow_volume_total_yesterday                              NUMERIC
  ,gas_flow_orifice_diameter                                    NUMERIC
  ,gas_flow_orifice_upstream_pipe_internal_diameter             NUMERIC
  ,gas_gathering_pressure                                       NUMERIC
  ,gas_gathering_pressure_average_yesterday                     NUMERIC
  ,lcv_output                                                   NUMERIC
  ,lcv_position_feedback                                        NUMERIC
  ,motor_current                                                NUMERIC
  ,motor_power                                                  NUMERIC
  ,motor_speed                                                  NUMERIC
  ,motor_torque                                                 NUMERIC
  ,pcv_output                                                   NUMERIC
  ,pcv_position_feedback                                        NUMERIC
  ,pump_speed_actual                                            NUMERIC
  ,pump_speed_average_yesterday                                 NUMERIC
  ,pump_torque                                                  NUMERIC
  ,pump_torque_average_yesterday                                NUMERIC
  ,pump_torque_max_today                                        NUMERIC
  ,pump_to_vsd_speed_command                                    NUMERIC
  ,separator_differential_pressure                              NUMERIC
  ,separator_gas_pressure                                       NUMERIC
  ,separator_level                                              NUMERIC
  ,separator_pressure_average_yesterday                         NUMERIC
  ,separator_pressure_max_today                                 NUMERIC
  ,sheave_ratio                                                 NUMERIC
  ,tubing_flow_meter                                            NUMERIC
  ,tubing_pressure                                              NUMERIC
  ,tubing_pressure_average_yesterday                            NUMERIC
  ,tubing_size_type                                             DATE
  ,vsd_frequency                                                NUMERIC
  ,vsd_mode                                                     VARCHAR(32)
  ,vsd_output                                                   NUMERIC
  ,vsd_running                                                  BOOLEAN
  ,vsd_temperature                                              NUMERIC
  ,wec_pcp_efficiency                                           NUMERIC
  ,wec_pcp_efficiency_alarm                                     NUMERIC
  ,wec_pcp_theoretical_pump_displacement                        NUMERIC
  ,wec_pump_max_speed_setpoint                                  NUMERIC
  ,wec_pump_min_speed_setpoint                                  NUMERIC
  ,wec_pump_speed_sampled_average                               NUMERIC
  ,wec_pump_speed_setpoint                                      NUMERIC
  ,wec_pump_trip                                                VARCHAR(32)
  ,wec_slow_pump_to_min_speed_command                           VARCHAR(32)
  ,water_flow_avg_5m                                            NUMERIC
  ,water_flow_mag_from_separator                                NUMERIC
  ,water_flow_mag_from_separator_total_yesterday                NUMERIC
  ,water_flow_wedge_sampled_average                             NUMERIC
  ,water_flow_wedge_total_yesterday                             NUMERIC
  ,water_gathering_pressure                                     NUMERIC
  ,water_gathering_pressure_average_yesterday                   NUMERIC
  ,wedgemeter_water_flow_avg_5m                                 NUMERIC
  ,wellhead_flow_configuration                                  VARCHAR(32)
  ,wellhead_state                                               VARCHAR(32)
  ,wellhead_status                                              NUMERIC
  ,wellhead_type                                                VARCHAR(32)
);
```

### Further information. What did you do, what did you expect?

I expected my models to be generated like they always do.

**Comment by aarondl** [comment]
Hey @nicored. I'll hopefully get time to look at this tonight. Sorry for such a disastrous bug. :(

**Comment by nicored** [comment]
No worries :) I am currently in the middle a hackathon so I'll try different approaches and see if they work

**Comment by aarondl** [comment]
Oh. I notice you're on a slightly older version. You could try 2.2.0 though I'm not 100% sure it'll improve things.

**Comment by nicored** [comment]
kk, will try now

**Comment by nicored** [comment]
And it worked!!!!!! You just saved me a couple of hours. I owe you a beer
